config/routes.rb
Rails.application.routes.draw do
  
  #get '/map_students'
  #get 'map_students', to: 'map_students#new'
  resources :map_students do
    collection {post :import}
  end
  resources :events
  resources :my_schedules
  get 'users/new'
  get  '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'

  get 'events/new'
  get '/events', to: 'events#new'

  get 'students/new'
  get '/students', to: 'students#index'
  #get '/students', to: 'students#new'
  #post '/students', to: 'students#create'

  get 'pages/dashboard'
  get '/dashboard', to:'pages#dashboard'

  #get 'pages/student'
  #get '/student', to: 'pages#student'

  #get 'pages/factulities'
  get 'factualities/new'
  get '/factualities', to: 'factualities#index'


  #get 'pages/myschedule'
  get 'my_schedules/new'
  get '/my_schedules', to: 'my_schedules#index'

  
  get 'sessions/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  

  resources :factualities
  resources :students 
  resources :users
  	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root 'pages#home'
end

app/models/factuality.rb
class Factuality < ApplicationRecord
	validates :mobile_no, length: {maximum: 10},
						  presence: true
	#belongs_to :organisation
end

app/controllers/factualities_controller.rb
class FactualitiesController < ApplicationController
  before_action :set_factuality, only: [:show, :edit, :update, :destroy]

  # GET /factualities
  # GET /factualities.json
  def index
    @factualities = Factuality.all
  end

  # GET /factualities/1
  # GET /factualities/1.json
  def show
  end

  # GET /factualities/new
  def new
    @factuality = Factuality.new
  end

  # GET /factualities/1/edit
  def edit
  end

  # POST /factualities
  # POST /factualities.json
  def create
    @factuality = Factuality.new(factuality_params)

    respond_to do |format|
      if @factuality.save
        format.html { redirect_to @factuality, notice: 'Factuality was successfully created.' }
        format.json { render :show, status: :created, location: @factuality }
      else
        format.html { render :new }
        format.json { render json: @factuality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /factualities/1
  # PATCH/PUT /factualities/1.json
  def update
    respond_to do |format|
      if @factuality.update(factuality_params)
        format.html { redirect_to @factuality, notice: 'Factuality was successfully updated.' }
        format.json { render :show, status: :ok, location: @factuality }
      else
        format.html { render :edit }
        format.json { render json: @factuality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /factualities/1
  # DELETE /factualities/1.json
  def destroy
    @factuality.destroy
    respond_to do |format|
      format.html { redirect_to factualities_url, notice: 'Factuality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factuality
      @factuality = Factuality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def factuality_params
      params.require(:factuality).permit(:teachers_name, :mobile_no)
    end
end

app/helpers/factualities_helper.rb
module FactualitiesHelper
end

app/views/factualities/_form.html.erb
<%= form_for(factuality) do |f| %>
  <% if factuality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(factuality.errors.count, "error") %> prohibited this factuality from being saved:</h2>

      <ul>
      <% factuality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :teachers_name %>
    <%= f.text_field :teachers_name %>
  </div>

  <div class="field">
    <%= f.label :mobile_no %>
    <%= f.number_field :mobile_no %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/factualities/edit.html.erb
<h1>Editing Factuality</h1>

<%= render 'form', factuality: @factuality %>

<%= link_to 'Show', @factuality %> |
<%= link_to 'Back', factualities_path %>

app/views/factualities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faculties</h1>

<table>
  <thead>
    <tr>
      <th>Teachers name</th>
      <th>Mobile no</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @factualities.each do |factuality| %>
      <tr>
        <td><%= factuality.teachers_name %></td>
        <td><%= factuality.mobile_no %></td>
        
        <td><%= link_to 'Edit', edit_factuality_path(factuality) %></td>
        <td><%= link_to 'Destroy', factuality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to 'New Factuality', new_factuality_path %></button>

app/views/factualities/new.html.erb
<h1>New Factuality</h1>

<%= render 'form', factuality: @factuality %>

<%= link_to 'Back', factualities_path %>

app/views/factualities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teachers name:</strong>
  <%= @factuality.teachers_name %>
</p>

<p>
  <strong>Mobile no:</strong>
  <%= @factuality.mobile_no %>
</p>

<%= link_to 'Edit', edit_factuality_path(@factuality) %> |
<%= link_to 'Back', factualities_path %>