config/routes.rb
Rails.application.routes.draw do
  
  #get '/map_students'
  #get 'map_students', to: 'map_students#new'
  resources :map_students do
    collection {post :import}
  end
  resources :events
  resources :my_schedules
  get 'users/new'
  get  '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'

  get 'events/new'
  get '/events', to: 'events#new'

  get 'students/new'
  get '/students', to: 'students#index'
  #get '/students', to: 'students#new'
  #post '/students', to: 'students#create'

  get 'pages/dashboard'
  get '/dashboard', to:'pages#dashboard'

  #get 'pages/student'
  #get '/student', to: 'pages#student'

  #get 'pages/factulities'
  get 'factualities/new'
  get '/factualities', to: 'factualities#index'


  #get 'pages/myschedule'
  get 'my_schedules/new'
  get '/my_schedules', to: 'my_schedules#index'

  
  get 'sessions/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  

  resources :factualities
  resources :students 
  resources :users
  	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root 'pages#home'
end

app/models/my_schedule.rb
class MySchedule < ApplicationRecord
	
end

app/controllers/my_schedules_controller.rb
class MySchedulesController < ApplicationController
  before_action :set_my_schedule, only: [:show, :edit, :update, :destroy]

  # GET /my_schedules
  # GET /my_schedules.json
  def index
    @my_schedules = MySchedule.all
  end

  # GET /my_schedules/1
  # GET /my_schedules/1.json
  def show
  end

  # GET /my_schedules/new
  def new
    @my_schedule = MySchedule.new
  end

  # GET /my_schedules/1/edit
  def edit
  end

  # POST /my_schedules
  # POST /my_schedules.json
  def create
    @my_schedule = MySchedule.new(my_schedule_params)

    respond_to do |format|
      if @my_schedule.save
        format.html { redirect_to @my_schedule, notice: 'My schedule was successfully created.' }
        format.json { render :show, status: :created, location: @my_schedule }
      else
        format.html { render :new }
        format.json { render json: @my_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_schedules/1
  # PATCH/PUT /my_schedules/1.json
  def update
    respond_to do |format|
      if @my_schedule.update(my_schedule_params)
        format.html { redirect_to @my_schedule, notice: 'My schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_schedule }
      else
        format.html { render :edit }
        format.json { render json: @my_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_schedules/1
  # DELETE /my_schedules/1.json
  def destroy
    @my_schedule.destroy
    respond_to do |format|
      format.html { redirect_to my_schedules_url, notice: 'My schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_schedule
      @my_schedule = MySchedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_schedule_params
      params.require(:my_schedule).permit(:course_name, :subjects, :start_time, :time, :duration, :date)
    end
end

app/helpers/my_schedules_helper.rb
module MySchedulesHelper
end

app/views/my_schedules/_form.html.erb
<%= form_for(my_schedule) do |f| %>
  <% if my_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_schedule.errors.count, "error") %> prohibited this my_schedule from being saved:</h2>

      <ul>
      <% my_schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_name %>
    <%= f.text_field :course_name %>
  </div>

  <div class="field">
    <%= f.label :subjects %>
    <%= f.text_field :subjects %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.text_field :start_time %>
  </div>

  

  <div class="field">
    <%= f.label :duration %>
    <%= f.time_select :duration %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_schedules/edit.html.erb
<h1>Editing My Schedule</h1>

<%= render 'form', my_schedule: @my_schedule %>

<%= link_to 'Show', @my_schedule %> |
<%= link_to 'Back', my_schedules_path %>

app/views/my_schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Course name</th>
      <th>Subjects</th>
      <th>Start time</th>
      
      <th>Duration</th>
      <th>Date</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_schedules.each do |my_schedule| %>
      <tr>
        <td><%= my_schedule.course_name %></td>
        <td><%= my_schedule.subjects %></td>
        <td><%= my_schedule.start_time %></td>
        
        <td><%= my_schedule.duration %></td>
        <td><%= my_schedule.date %></td>
        
        <td><%= link_to 'Reschedule', edit_my_schedule_path(my_schedule) %></td>
        <td><%= link_to 'Cancel calss', my_schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to 'New My Schedule', new_my_schedule_path %></button>

app/views/my_schedules/new.html.erb
<h1>New My Schedule</h1>

<%= render 'form', my_schedule: @my_schedule %>

<%= link_to 'Back', my_schedules_path %>

app/views/my_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course name:</strong>
  <%= @my_schedule.course_name %>
</p>

<p>
  <strong>Subjects:</strong>
  <%= @my_schedule.subjects %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @my_schedule.start_time %>
</p>



<p>
  <strong>Duration:</strong>
  <%= @my_schedule.duration %>
</p>

<p>
  <strong>Date:</strong>
  <%= @my_schedule.date %>
</p>

<%= link_to 'Edit', edit_my_schedule_path(@my_schedule) %> |
<%= link_to 'Back', my_schedules_path %>